name: google_maps_webservice
description: Google Maps Web Services [API](https://developers.google.com/maps/web-services)
version: 1.0.0
homepage: https://github.com/lejard-h/google_maps_webservice

environment:
  sdk: ^3.7.0

dependencies:
  http: ^1.3.0
  meta: ^1.3.0
  json_annotation: ^4.0.0

dev_dependencies:
  build_runner: ^2.4.15
  coverage: ^1.0.0
  json_serializable: ^6.9.4
  lints: ^5.1.1
  test: ^1.16.0
